### ISSUE TITLE
Follow Up Ultrasonic Sensors

### ISSUE THREAD

**Issue by omaresl** [ivonnerobless/HOC#11]
Ask to Adan for the code and merge into the master branch.

**Comment by ivonnerobless** [comment]
Adan said that had an issue with the ports, cause he just create the code for only one sensor

**Comment by omaresl** [comment]
He redefine the same macro in his code (when he tried to add more pins). He must rename each macro for each pin

**Comment by ivonnerobless** [comment]
ok i got it let me tell him

**Comment by omaresl** [comment]
First delivery for ultrasonic sensors integrated.
