### ISSUE TITLE
Working Plan Update for Integration phase 1

### ISSUE THREAD

**Issue by omaresl** [ivonnerobless/HOC#19]
We need update the working plan before continue with the activities. The last plan is very delayed and it's not been taken in account for the activities (Perhaps you have the plan updated but only is visible for you locally) The idea is check which activities are finished and which activities are coming to plan how we manage the time that we have.

**This issue has High Importance and is Urgent**

**Comment by omaresl** [comment]
If this issue is not solved ASAP (as soon as possible) all the project must be in risk. (Already is in risk)

**Comment by ivonnerobless** [comment]
Work plan updated

**Comment by omaresl** [comment]
The name of the file finish with "(1)" Remove that.

**Comment by omaresl** [comment]
The issue must be closed once a commit solve this topic
