### ISSUE TITLE
HW SW Interface

### ISSUE THREAD

**Issue by omaresl** [ivonnerobless/HOC#21]
In the Updated Planning the HW SW Interface is at 100% (Completed) Where I can find the file to check the interface?

**Comment by ivonnerobless** [comment]
You can find it in trello

**Comment by omaresl** [comment]
Add it into the project as well.

**Comment by ivonnerobless** [comment]
ok i got it

**Comment by omaresl** [comment]
The issue must be closed once the file is controlled in github. At this moment there is any commit that solve this topic.

**Comment by ivonnerobless** [comment]
Done!
